---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hellodeploy.yaml
  - hellosvc.yaml
  - helloroute.yaml
images:
  - name: quay.io/redhattraining/versioned-hello:v1.0
    newTag: v1.0
