apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
    arbitary.annationation: "asdf"
  name: cluster
spec:
  disableAllDefaultSources: false
